code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.project-manager
code --install-extension bradgashler.htmltagwrap
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-ionic-snippets
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.vscode-pull-request-github
code --install-extension gitlab.gitlab-workflow
code --install-extension ionic.ionic
code --install-extension mhutchie.git-graph
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.live-server
code --install-extension oderwat.indent-rainbow
code --install-extension pranaygp.vscode-css-peek
code --install-extension realappie.ionicons
code --install-extension vmware.vscode-boot-dev-pack
code --install-extension vscjava.vscode-spring-initializr
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.javascriptsnippets
code --install-extension zignd.html-css-class-completion
